version: 2
sources:
  - name: bronze
    database: iceberg
    schema: bronze
    tables:
      - name: prices
        loaded_at_field: "_ingested_at"
        freshness:
          warn_after: { count: 30, period: hour }
          error_after: { count: 48, period: hour }